version: '3.8'

# Cal.com development stack with Zoho Calendar fixes
# Builds from root directory using Dockerfile.root (includes all fixes)

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendso
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  calcom:
    build:
      context: .
      dockerfile: Dockerfile.root
      args:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/calendso
        DATABASE_DIRECT_URL: postgresql://postgres:postgres@postgres:5432/calendso
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: your-secret-key-here-change-in-production
        CALENDSO_ENCRYPTION_KEY: your-encryption-key-here-change-in-production
        NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
        NEXT_PUBLIC_LICENSE_CONSENT: agree
        CALCOM_TELEMETRY_DISABLED: 1
        ZOHOCALENDAR_CLIENT_ID: ${ZOHOCALENDAR_CLIENT_ID:-}
        ZOHOCALENDAR_CLIENT_SECRET: ${ZOHOCALENDAR_CLIENT_SECRET:-}
    image: ghcr.io/writepavel/cal.com:root-zoho-fix
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/calendso
      DATABASE_DIRECT_URL: postgresql://postgres:postgres@postgres:5432/calendso
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key-here-change-in-production
      CALENDSO_ENCRYPTION_KEY: your-encryption-key-here-change-in-production
      NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
      NEXT_PUBLIC_LICENSE_CONSENT: agree
      CALCOM_TELEMETRY_DISABLED: 1
      ZOHOCALENDAR_CLIENT_ID: ${ZOHOCALENDAR_CLIENT_ID:-}
      ZOHOCALENDAR_CLIENT_SECRET: ${ZOHOCALENDAR_CLIENT_SECRET:-}
    restart: unless-stopped

volumes:
  postgres_data: